name: summary
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.0
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - autocorrect=2.6.1
  - aws-c-auth=0.7.4
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.3
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.13
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.6
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.23.1
  - aws-sdk-cpp=1.11.156
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - catalogue=2.0.10
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - confection=0.1.3
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataclasses=0.8
  - datasets=2.14.5
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - ffmpeg=4.3
  - filelock=3.12.4
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - huggingface_hub=0.17.3
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_console=6.6.3
  - jupyter_core=5.3.2
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=13.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcurl=8.3.0
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.57.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=4.23.4
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lightgbm=4.0.0
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=3.0.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - murmurhash=1.0.10
  - nbclient=0.8.0
  - nbconvert=7.8.0
  - nbconvert-core=7.8.0
  - nbconvert-pandoc=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - networkx=3.1
  - nltk=3.8.1
  - notebook=7.0.4
  - notebook-shim=0.2.3
  - numpy=1.26.0
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.3
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.1
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathy=0.10.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - preshed=3.0.9
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=13.0.0
  - pycparser=2.21
  - pydantic=1.10.13
  - pygments=2.16.1
  - pysocks=1.7.1
  - pyspellchecker=0.7.2
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-xxhash=3.3.0
  - python_abi=3.10
  - pytorch=2.1.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qtconsole-base=5.4.4
  - qtpy=2.4.0
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - regex=2023.10.3
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.6.0
  - rpds-py=0.10.3
  - s2n=1.3.51
  - sacremoses=0.0.53
  - safetensors=0.3.3
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shellingham=1.5.3
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.6.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.4.8
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.10.0
  - terminado=0.17.1
  - thinc=8.1.12
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.13.3
  - tomli=2.0.1
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.1
  - transformers=4.33.3
  - typer=0.9.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucx=1.14.1
  - uri-template=1.3.0
  - urllib3=2.0.5
  - wasabi=1.1.2
  - wcwidth=0.2.8
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.3
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
